name: 'Convert JSON to ENV'

description: 'Github Actions to convert variables from a JSON file to workflow ENV variables :octocat:'

inputs:
  json_file:
    description: JSON file to convert to env variable
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository content
      uses: actions/checkout@v2 # Checkout the repository content to github runner.

    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Install the python version needed

    # - name: Install Python dependencies
    #   run: python -m pip install --upgrade pip requests

    - name: Execute Python script # Run the run.py to get the latest data
      run: python ${{ github.action_path }}/convert.py ${{ inputs.json_file }}
      shell: bash

# branding:
#     icon: 'git-commit'
#     color: 'black'