name: Action test on Macos

on:
  push:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/convert-json-to-env@main
        with:
          json_file: ./config.json
      - run: echo ${{ env.KEY1 }}
      - run: echo ${{ env.KEY2 }}